In [1]:
import numpy as np

In [2]:
##nd array
# unified array type, elementwise operations
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
print(array_a)

[1 2 3]


In [6]:
array_a.shape

(3,)

In [8]:
array_b=np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_b.shape

(2, 3)

In [10]:
#rows only
array_b.shape[0]

2

In [11]:
#col only
array_b.shape[1]

3